

services:

  # ==============================
  # 1. Spring Boot Backend
  # ==============================
  backend:
    build: ./backend
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      - fastapi
    environment:
      - FASTAPI_URL=http://fastapi:8001/query
    networks:
      - zaun-network

  # ==============================
  # 2. FastAPI Moderation / AI
  # ==============================
  fastapi:
    build: ./fastapi
    container_name: fastapi-service
    ports:
      - "8001:8001"
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434
    networks:
      - zaun-network

  # ==============================
  # 3. Ollama AI Server
  # ==============================
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    # If you have local models, mount them
    # volumes:
    #   - ./models:/models
    networks:
      - zaun-network

  # ==============================
  # 4. React Frontend
  # ==============================
  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - fastapi
    networks:
      - zaun-network

# ==============================
# Shared Network
# ==============================
networks:
  zaun-network:
    driver: bridge
