version: '3.9'
services:
  fastapi:
    build: ./fastapi
    ports:
      - "8001:8001"

  springboot:
    build: ./backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - fastapi
      - springboot

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
